### ISSUE TITLE
USER_VALS Table is not used 

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#1]
In *DataBase* class the *USER_VALS* table is created but it is never used and it has no Entity class (other tables have they own class representations).

The *LoadUserItem()* is used but all usages of the *SaveUserItem()* are commented out.
Because both *LoadUserItem()* and *SaveUserItem()* are used without entity class (all other database operations are done with use of entity classes) I removed unused *SaveUserItem()* method.
The *LoadUserItem()* is still there so the project can be compiled. But it is useless since there are no saving operations.

There is need to investigate why the *USER_VALS* table was existing at all and do we still need it.

/cc @SoftwareEngineeringProjectCEIE/all

**Comment by przezor** [comment]
@tomasz-buchta Chciałbyś looknąć i solvnąć? :)

**Comment by przezor** [comment]
@tomasz-buchta ? :>
