### ISSUE TITLE
Load... methods can return null value

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#3]
There are three **Load** methods in **DataBase.cs** file.
In some cases they may return null value.

This behavior causes NullPointExceptions in other parts of the project.
But instead of providing null checks we can **Null Object** design patter.

In other words. Instead of:

    if (result != null) { ... }

those methods should return empty lists.
I assign @rysiacz to this task.

Example for you:

    public List<object> LoadObjects()
    {
        List<object> result = new List<object>();
        // some actions
        if (error)
        {
            return null;
        }
        else
        {
            return result;
        }
    }

Such code should be changed into:

    public List<object> LoadObjects()
    {
        List<object> result = new List<object>();
        // some actions
        if (error)
        {
            return new List<object>();
        }
        else
        {
            return result;
        }
    }

Try to hunt down all such cases.
You have three such methods inside **DataBase.cs** file for sure, but look for it in other files as well.

Remember to compile project before commiting the result.

**Comment by przezor** [comment]
@rysiacz Dasz rade to ogarnąć w tym tygodniu?

**Comment by rysiacz** [comment]
Yes, I have done it today in bug/null branch. Please review it.

**Comment by przezor** [comment]
Awesome! @rysiacz please assign someone to review it :)

**Comment by rysiacz** [comment]
@gabr, could you?
