### ISSUE TITLE
catch (Exception) {}

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#4]
Project contains a lot of

    try
    {
        ...
    }
    catch (Exception)
    {
    }

and no method to log errors.

We need:

1. Module to create application logs of different types (info, warning, error)
2. Log all empty catches as well as catches that just returns **false** or **null**

Proposition of log syntax:

    DateTime; Area; Type; Message

Where:

* DateTime - information when the log was created (**DateTime.Now.ToString()** should be enough)
* Area - file name when the log was created (you can automate this one like [that](http://stackoverflow.com/questions/3095696/how-do-i-get-the-calling-method-name-and-type-using-reflection))
* Type - info, warning, error
* Message - message without line breaks and semicolons

I think this task can be handled by @tomasz-buchta

**Comment by przezor** [comment]
@tomasz-buchta How is it going?

**Comment by przezor** [comment]
@tomasz-buchta?
