### ISSUE TITLE
OutOfMemory in AnalyzeNodeChildren()

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#5]
There is a method **AnalyzeNodeChildren()** in **XMLLoogic.cs** file.

And the line 44 causes the OutOfMemoryException.
The method is calling itself so the recursion may causes a problem.

Three things to do here:
1. Check what the method is really doing
2. Check if it can be fixed (probably some additional conditions will do the job)
3. In case when the recursion is the problem it will have to be rewritten into iterative form

To reproduce error:
1. Add XML file and go to the *Compare* tab
2. Add "test" text into *Parameter Name* text box
3. Press *compare* button

I think @kkoscielniak can handle it.

**Comment by przezor** [comment]
@kkoscielniak Jak progress?

**Comment by kkoscielniak** [comment]
@przezor chwilowo nie mogłem się tym zająć - projekt nie kompiluje się w Xamarin, muszę zainstalować Windows. Sorry za dzień obsuwy w odpowiedzi.

**Comment by gabr** [comment]
Try to use (mono)[http://www.mono-project.com/Mono:OSX/]
My boss at work a few days ago used it to successfully compile and run quite complicated c# project.

**Comment by kkoscielniak** [comment]
Xamarin == mono for os x :)

W dniu poniedziałek, 30 listopada 2015 Arkadiusz Gabryś <
notifications@github.com> napisał(a):

**Comment by przezor** [comment]
@kkoscielniak Oki :)

**Comment by przezor** [comment]
kurde..

**Comment by przezor** [comment]
@kkoscielniak Jak tam progres? :)

**Comment by przezor** [comment]
@kkoscielniak Jeśli nie możesz tego zrobić bo Ci komp nie śmiga.., to zagadaj kogoś z teamu i mu przekaż tego taska, jeśli się zgodzi. Ok?

**Comment by kkoscielniak** [comment]
@przezor ogarnę sobie windowsa w weekend i to zrobię ;-)

**Comment by przezor** [comment]
@kkoscielniak ???

**Comment by kkoscielniak** [comment]
Working on it.

**Comment by kkoscielniak** [comment]
@przezor @gabr I still have issues regarding Windows installation on my computer. Thus I might need some help later. 

I will analyze the code and propose solutions, yet perhaps @gabr should check whether this works properly.

**Comment by gabr** [comment]
Okej, so I've tested it and It appears that bug is gone.
One of the other issues had to be connected with this problem.

I'm closing the issue, because there is nothing to fix.
