### ISSUE TITLE
"Tags" tab seems to not work at all

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#6]
Anything seems to work in "Tags" tab.

I will investigate all controls and all functions and make it work.

**Comment by przezor** [comment]
How is it going? :)

**Comment by gabr** [comment]
I started yesterday, didn't found the issue yet.
After #3 it will be easier to find the bug.

**Comment by przezor** [comment]
Ok. Thanks for info

**Comment by gabr** [comment]
Need a review
At the beginning I was thinking that this **Tags** tab is for managing Tags inside XMl files. But it's not.
It purpose is to assign labels to files to find them easily in searcher.

After analyzing the **Tags** tab in the application I found out that it generally works but after saving/opening the database all saved tags disappears.

After fixing this one I noticed that *Assigned tags* was not updating when selecting XML files on the list.
This one is fixed as well.

To review this functionalities I assign @szpaqq because he is already familiar in clicking out functions in application.

Doing so I made some style and optimization improvements as well.
So it would be the best if @kkoscielniak looked at the code as well.

**Comment by kkoscielniak** [comment]
Fine, I will do the code review right now.

**Comment by gabr** [comment]
I see you merged the request, did you check the functionality as well?
As I remember you were not able to run this program then how?

**Comment by kkoscielniak** [comment]
Code review is not about the testing. I can see code changes are following our CR rules. You can ask the test team to check whether it's working well. 

For me the code is fine.

**Comment by gabr** [comment]
I did ask @szpaqq for functionality test.

> To review this functionalities I assign @szpaqq because he is already familiar in clicking out functions in application.

**Comment by kkoscielniak** [comment]
fine, let's wait for his response then

**Comment by przezor** [comment]
@szpaqq ??
