### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by gabr** [SoftwareEngineeringProjectCEIE/SourceCode#9]
In **Form1.cs** the path *config.ini* is used twice in two different places.

The task is to create one constant value instead of this hardcoded path.

**Comment by rysiacz** [comment]
Done. Please @kkoscielniak to review it.

**Comment by gabr** [comment]
This variable should be private and constants names are capitalized with underscore as a word separator.

**Comment by kkoscielniak** [comment]
@rysiacz I confirm that constants should be written in the way @gabr proposed.

**Comment by gabr** [comment]
Don't close until it is done correctly and merged.

**Comment by przezor** [comment]
@rysiacz ?

**Comment by przezor** [comment]
@gabr @rysiacz ???

**Comment by rysiacz** [comment]
Done. 
@gabr @kkoscielniak please check again.

**Comment by gabr** [comment]
Try follow this [examples](https://msdn.microsoft.com/pl-pl/library/dobre-i-zle-praktyki-w-c-sharp--czesc-1.aspx).

    private cont int CONSTANT_VALUE = 1;

**Comment by rysiacz** [comment]
@gabr please try to be more consistent in your instructions capitalized !=uppercase.
Corrected again.

**Comment by kkoscielniak** [comment]
@rysiacz is it merged already? 

If yes, I'd like to close the issue.
